apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: argocd-server
        image: argoproj/argocd:v2.13.2
